### ISSUE TITLE
Sign in / Sign up forms have overflowing fields

### ISSUE THREAD

**Issue by monarchwadia** [Mintbean/DevCollective.io#30]
![image](https://user-images.githubusercontent.com/4856944/120894512-c6990880-c5e6-11eb-89c6-b31e6f44f68c.png)
![image](https://user-images.githubusercontent.com/4856944/120894515-ca2c8f80-c5e6-11eb-8876-2099ab2e6ca1.png)

**Comment by monarchwadia** [comment]
Note that I have the Lastpass chrome extension, which might be causing the problem?

**Comment by CrappyDill** [comment]
I didn’t notice that last night working on those fields, but I will check again.

**Comment by CrappyDill** [comment]
I doubled checked and the form looks good on my end.

**Comment by monarchwadia** [comment]
This is fixed.
